// <auto-generated />
namespace DAFA.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180623ValidationMessageshouldbeignoredatEventWarningtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180623ValidationMessageshouldbeignoredatEventWarningtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201806231719165_20180623 - ValidationMessage should be ignored at EventWarning table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
