// <auto-generated />
namespace DAFA.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180623SolvedDateaddedtoEventWarningtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180623SolvedDateaddedtoEventWarningtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201806231715568_20180623 - Solved Date added to Event Warning table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
