// <auto-generated />
namespace DAFA.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180325Entititesconfigurationfilesadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180325Entititesconfigurationfilesadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251927519_20180325 - Entitites configuration files added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
